feat/Добавить REST full эндпоинты
PetrVladimirovich/java-filmorate pull request #4
Opened 2022-12-15 17:05 UTC by PetrVladimirovich

2022-12-16 14:16 UTC, krylov-sergey-sergeevich requested changes
Привет, хорошая работа, давай поправим моменты
1) По возможности везде глянуть и убрать дублирование кода
2) Аннотацию от ломбока чтобы конструкторы не писать
3) Необязательно: Можно подумать и сделать интерфейс с дженериком AbstractStorage и туда вынести похожие действия

Буду ждать с доработками =)

2022-12-16 14:16 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @Autowired
Давай добавим аннотацию от ломбок для того чтобы конструктор не писать

2022-12-16 14:16 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +@RequestMapping("/users")
Давай добавим аннотацию от ломбок для того чтобы конструктор не писать

2022-12-16 14:16 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            log.info("Недопустимые значения полей : " + message);
log.error наверно

2022-12-16 14:16 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +@RequestMapping("/users")
И давай уберем дублирование в коде

2022-12-16 14:16 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +public class FilmService {
Давай добавим аннотацию от ломбок для того чтобы конструктор не писать

2022-12-16 14:16 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/InMemoryUserStorage.java
> +public class InMemoryUserStorage implements UserStorage {
Дубли убрать

2022-12-17 13:52 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - отлично, зачет!

2022-12-17 13:52 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/Constants.java
> +    public static void requestBodyValidationLogs(BindingResult bindingResult) {
Хорошее решение

2022-12-17 13:52 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/AbstractStorage.java
> +public interface AbstractStorage<T> {
Можно было так-же добавить

getById
getAll 

Но это не критично - отлично что получилось =)

2022-12-17 13:52 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/AbstractStorage.java
> +    void add(T t);
Рекомендую возвращать T

2022-12-17 13:52 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/AbstractStorage.java
> +    void update(T t);
Рекомендую возвращать T

2022-12-17 14:15 UTC, PetrVladimirovich commented on src/main/java/ru/yandex/practicum/filmorate/storage/AbstractStorage.java
> +    void add(T t);
Почему? ))

2022-12-17 14:15 UTC, merged